secrets: "{{.Secrets}}"
env: "{{.Env}}"
http:
  host: localhost
  port: 8080
  expire: 1440
database:
  host: localhost
  port: 5432
  name: "itpkg_{{.Env}}"
  user: postgres
  password: "{{.DbPassword}}"
  sslmode: disable

redis:
  host: localhost
  port: 6379
  db: 6
